"""Add tutor_guidance and narrative_context to tasks

Revision ID: a3272ac954e2
Revises: c2450619bb0d
Create Date: 2025-12-31 16:22:28.803440

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3272ac954e2'
down_revision: str | Sequence[str] | None = 'c2450619bb0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tutor_guidance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('narrative_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'narrative_context')
    op.drop_column('tasks', 'tutor_guidance')
    # ### end Alembic commands ###
