"""add_requires_submission_to_tasks

Revision ID: 09975b8c1d6c
Revises: d187d5f7ad45
Create Date: 2026-01-04 19:07:03.034163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09975b8c1d6c"
down_revision: str | Sequence[str] | None = "d187d5f7ad45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("requires_submission", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "requires_submission")
    # ### end Alembic commands ###
