"""Add tutor_persona and workspace_type to tasks

Revision ID: 0a6a975f3c66
Revises: 965c76772f9f
Create Date: 2026-02-04 16:34:21.056323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a6a975f3c66"
down_revision: str | Sequence[str] | None = "965c76772f9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("tutor_persona", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "tutor_persona")
    # ### end Alembic commands ###
