"""add_lti_launches

Revision ID: 87a33b9dfbb7
Revises: f95d2d11a478
Create Date: 2026-02-20 19:09:40.595809

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87a33b9dfbb7"
down_revision: str | Sequence[str] | None = "f95d2d11a478"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lti_launches",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("lti_sub", sa.String(), nullable=False),
        sa.Column("ags_lineitems", sa.Text(), nullable=True),
        sa.Column("ags_scope", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_lti_launches_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_launches")),
    )
    op.create_index(
        "idx_lti_launch_learner_project", "lti_launches", ["learner_id", "project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lti_launch_learner_project", table_name="lti_launches")
    op.drop_table("lti_launches")
    # ### end Alembic commands ###
