"""add_workspace_type_to_tasks

Revision ID: 965c76772f9f
Revises: 09975b8c1d6c
Create Date: 2026-02-04 10:43:09.129658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "965c76772f9f"
down_revision: str | Sequence[str] | None = "09975b8c1d6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("workspace_type", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "workspace_type")
    # ### end Alembic commands ###
