"""Add summary field to tasks

Revision ID: d187d5f7ad45
Revises: a3272ac954e2
Create Date: 2026-01-04 15:42:41.184153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd187d5f7ad45'
down_revision: Union[str, Sequence[str], None] = 'a3272ac954e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'summary')
    # ### end Alembic commands ###
