"""add_lti_user_mappings

Revision ID: f95d2d11a478
Revises: 0a6a975f3c66
Create Date: 2026-02-20 14:00:00.760704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95d2d11a478'
down_revision: Union[str, Sequence[str], None] = '0a6a975f3c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_user_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lti_sub', sa.String(), nullable=False),
    sa.Column('lti_iss', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_lti_user_mappings_learner_id_learners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lti_user_mappings')),
    sa.UniqueConstraint('lti_sub', 'lti_iss', name='uq_lti_sub_iss')
    )
    op.create_index('idx_lti_mapping_learner', 'lti_user_mappings', ['learner_id'], unique=False)
    op.create_index('idx_lti_mapping_sub_iss', 'lti_user_mappings', ['lti_sub', 'lti_iss'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lti_mapping_sub_iss', table_name='lti_user_mappings')
    op.drop_index('idx_lti_mapping_learner', table_name='lti_user_mappings')
    op.drop_table('lti_user_mappings')
    # ### end Alembic commands ###
